language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"
  
install:
  - pip install codecov pytest pytest-cov
  - pip install --editable .

script:
  - export AWS_DEFAULT_REGION=ap-south-1
  - py.test --cov-report=xml --cov=kines tests/
 
after_success:
  - codecov
